### ISSUE TITLE
Error on video_classification.ipynb on Colab

### ISSUE THREAD

**Issue by steveice** [huggingface/notebooks#326] opened 2023-02-22 22:46 UTC
Hi, 

When I run this notebook "video_classification.ipynb" on the Colab.
There are two issues were observed on the notebook

1. RandomCrop on # Training dataset transformations.
   Is it correct to change the parameters to "feature_extractor.crop_size " or "(224,244)" or "size=224"?

2. When we train the model on the Colab (with batch_size = 2), the following error showed up. Can you suggest how to fix this issue?

<img width="1618" alt="Screenshot 2023-02-22 at 14 46 25" src="https://user-images.githubusercontent.com/1169928/220777552-85d3da4c-5a8e-4d3e-88a4-fad8888f9680.png">

Thank you!

**Comment by sayakpaul** [comment] 2023-02-25 05:15
This is probably because of a recent change introduced in `ImageProcessors`. 

We need to fetch the `size` like so: `PROCESSOR.size["shortest_edge"]`. This guide should be useful in resolving the issue you're facing: https://huggingface.co/docs/transformers/tasks/video_classification

**Comment by sayakpaul** [comment] 2023-03-03 10:22
@steveice would you like to open a PR fixing it?

**Comment by sayakpaul** [comment] 2023-03-03 14:58
Could you provide a minimally reproducible snippet?

**Comment by jansaldo** [comment] 2023-04-17 15:43
Hi! I've opened this [PR](https://github.com/huggingface/notebooks/pull/351) to address this issue. Hope you find it useful!

> @steveice would you like to open a PR fixing it?

**Comment by sayakpaul** [comment] 2023-04-18 21:00
With https://github.com/huggingface/notebooks/pull/351 being merged, this issue should be solved. Closing the issue.

**Closed by sayakpaul** 2023-04-18 21:00 UTC
